# Travis CI config
#
# Note: When updating, please also update .gitlab-ci.yml
language: python
dist: xenial  # required for Python >= 3.7
env:
  TOOLCHAIN_DIR="${HOME}/toolchain"

  ESP8266_BINDIR="${TOOLCHAIN_DIR}/xtensa-lx106-elf/bin"
  ESP32_BINDIR="${TOOLCHAIN_DIR}/xtensa-esp32-elf/bin"
  ESP32S2_BINDIR="${TOOLCHAIN_DIR}/xtensa-esp32s2-elf/bin"

  PATH="${PATH}:${ESP8266_BINDIR}:${ESP32_BINDIR}:${ESP32S2_BINDIR}"

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then ./test/ci/setup_ci_build_env.sh; fi

script:
  # test python components (fast)
  - python setup.py build
  # this is hacky, installing test script deps via pip as need to be in the virtualenv
  # but don't count if only in setup.py's .eggs dir, and "setup.py test" integration
  # doesn't allow running esptool.py as a script...
  - pip install pyserial pyelftools cryptography
  - python test/test_imagegen.py
  - python test/test_espsecure.py
  - pip install flake8 flake8-future-import  # matches tests_require in setup.py, a bit hacky
  - python setup.py flake8
  - python setup.py install
  - ( cd / && esptool.py --help )  # check the installed versions can run
  - ( cd / && espefuse.py --help )
  - ( cd / && espsecure.py --help )
  # build stub (Python 3 only)
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then make -C flasher_stub V=1; fi
  # check the just-built stub matches the one in esptool.py
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then cd flasher_stub && python ./compare_stubs.py; fi
